# Generated by Django 3.2.7 on 2022-03-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-name',)},
        ),
    ]
