# Generated by Django 3.2.7 on 2022-03-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',)},
        ),
    ]
