# Generated by Django 3.2.4 on 2021-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_photo_album_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='short_desc',
            field=models.TextField(default='this is a photo album photo_album_namephoto_album_namephoto_album_namephoto_album_name'),
            preserve_default=False,
        ),
    ]
