# Generated by Django 3.2.7 on 2021-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
