# Generated by Django 3.2.7 on 2021-11-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.CharField(blank=True, choices=[('visa-application', 'Visa Application'), ('test-preparation', 'Test Preparation'), ('consultation', 'Consultation')], max_length=20, null=True, verbose_name='Enquiry About'),
        ),
    ]
