# Generated by Django 3.2.7 on 2022-02-02 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('dob', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('grade_or_percent', models.CharField(max_length=10)),
                ('passed_year', models.CharField(max_length=10, verbose_name='Passed Year')),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=20, verbose_name='Marital Status')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers is allowed', regex='^[0-9]*$')])),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('guardian_contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers is allowed', regex='^[0-9]*$')])),
                ('country_to_apply', models.CharField(max_length=50)),
                ('desired_course', models.CharField(max_length=50)),
                ('taken_educational_institution', models.BooleanField()),
                ('chosen_educational_institution', models.CharField(max_length=255)),
                ('how_know_about_use', models.TextField()),
            ],
        ),
    ]
