# Generated by Django 3.2.7 on 2022-02-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0002_auto_20211031_0336'),
        ('contact', '0003_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='how_know_about_use',
            new_name='how_know_about_us',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='taken_educational_institution',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='taken_proficiency_test_and_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='chosen_educational_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='country_to_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_to_apply', to='study_abroad.country'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
