# Generated by Django 3.2.7 on 2021-10-27 15:04

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='main_image',
            field=models.ImageField(upload_to=services.models.get_events_main_image_uploadpath),
        ),
    ]
