# Generated by Django 3.2.7 on 2021-10-28 00:09

from django.db import migrations, models
import study_abroad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('main_image', models.ImageField(upload_to=study_abroad.models.get_country_main_image_uploadpath)),
            ],
        ),
    ]
