# Generated by Django 3.2.7 on 2021-10-30 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='summary',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
