# Generated by Django 3.2.7 on 2021-09-22 17:13

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=100, verbose_name='Reviewer Full Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Reviewer Designation')),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.get_reviewer_image_uploadpath, verbose_name='Image')),
                ('testimony', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
