# Generated by Django 3.2.7 on 2021-11-13 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn Profile Link'),
        ),
        migrations.AddField(
            model_name='member',
            name='msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
